Repository mozilla/remote-settings, pull requests merged in 2023-11, with the labels that each got.

#487 Replace dependabot automation action with groups feature
  .github/dependabot.yml
  .github/workflows/ci.yaml
Labels: enhancement

#494 Fix authors string in pyproject.toml
  Makefile
  pyproject.toml
Labels: python

#498 Remove mentions of CircleCI
  README.rst
  RemoteSettings.dockerignore
  docs/support.rst
Labels: documentation

#499 Upgrade kinto-attachment to 6.3.2
  poetry.lock
  pyproject.toml
Labels: dependencies

#501 Add instructions for manual deploy
  README.rst
Labels: documentation

#500 Use `ruff` instead of `flake8`, `isort`, and `black`
  .flake8
  Makefile
  kinto-remote-settings/src/kinto_remote_settings/changes/views.py
  kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py
  kinto-remote-settings/src/kinto_remote_settings/signer/backends/local_ecdsa.py
  kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py
  kinto-remote-settings/src/kinto_remote_settings/signer/updater.py
  kinto-remote-settings/tests/changes/test_changes.py
  kinto-remote-settings/tests/changes/test_utils.py
  kinto-remote-settings/tests/signer/test_events.py
  kinto-remote-settings/tests/signer/test_plugin_setup.py
  kinto-remote-settings/tests/signer/test_signer.py
  kinto-remote-settings/tests/signer/test_updater.py
  kinto-remote-settings/tests/signer/test_utils.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/integration/plugins/test_changes.py
  tests/integration/test_endpoints.py
Labels: python

#503 Update PROD deployment instruction for kinto-admin dev
  docs/tutorial-dev-kinto-admin.rst
Labels: documentation

#504 Mention approval run for prod deployment
  README.rst
Labels: documentation
