Repository mozilla/remote-settings, pull requests merged in 2023-10, with the labels that each got.

#469 Move dependabot automation action to workflows folder
  .github/workflows/dependabot-automation.yaml
Labels: bug

#472 feat: use `git describe --tags --abbrev=4` to tag images
  .circleci/config.yml
Labels: enhancement

#478 Migrate Docker container publishing workflow from Circle to GHA
  .circleci/config.yml
  .github/workflows/publish.yaml
  bin/deploy-dockerhub.sh
Labels: enhancement

#480 Add IDs to docker metadata steps for build/push input
  .github/workflows/publish.yaml
Labels: fix

#482 Add caching for web / test container builds in CI
  .github/workflows/ci.yaml
  Makefile
Labels: enhancement
