Repository mozilla/remote-settings, pull requests merged in 2024-02, with the labels that each got.

#540 Upgrade kinto-admin to 3.0.3
  RemoteSettings.Dockerfile
  bin/build-kinto-admin.sh
  bin/pull-kinto-admin.sh
  kinto-admin/VERSION
Labels: dependencies

#543 Upgrade kinto to 18.0.0
  bin/pull-kinto-admin.sh
  poetry.lock
  pyproject.toml
Labels: dependencies

#544 Upgrade all indirect dependencies
  poetry.lock
Labels: dependencies

#551 Fix #550: fix building of container on MacOS
  bin/pull-kinto-admin.sh
  poetry.lock
  pyproject.toml
Labels: bug

#552 Upgrade kinto-attachment to 6.4.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#557 Sign commit generated by github action for kinto-admin update
  .github/workflows/scheduled.yaml
Labels: enhancement

#554 Include Dependabot pull-requests in changelog
  .github/release.yml
Labels: dependencies
