Repository mozilla/remote-settings, pull requests merged in 2024-03, with the labels that each got.

#566 Browser-tests and integration-tests merge, paving trail for better gatekeeper tests
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  BrowserTests.Dockerfile
  BrowserTests.dockerignore
  Makefile
  README.rst
  RemoteSettings.Dockerfile
  docker-compose.yml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/integration/plugins/__init__.py
  tests/integration/plugins/test_attachment.py
  tests/integration/test_endpoints.py
  tests/plugins/__init__.py
  tests/plugins/test_attachment.py
  tests/plugins/test_changes.py
  tests/plugins/test_email.py
  tests/plugins/test_history.py
  tests/plugins/test_signer.py
  tests/run.sh
  tests/test_endpoints.py
  tests/test_review.py
  tests/utils.py
Labels: python

#572 Standardizing browser tests between environments
  README.rst
  kinto-remote-settings/tests/signer/test_events.py
  kinto-remote-settings/tests/signer/test_signoff_flow.py
  tests/conftest.py
  tests/test_review.py
Labels: fix

#574 Switching admin-pull to use alpine:3 image
  RemoteSettings.Dockerfile
  bin/pull-kinto-admin.sh
Labels: docker

#578 Fixing scheduled job PR creation
  .github/workflows/scheduled.yaml
Labels: fix

#579 Specify keyid for Autograph signing
  .secrets.baseline
  kinto-remote-settings/README.rst
  kinto-remote-settings/src/kinto_remote_settings/signer/backends/autograph.py
  kinto-remote-settings/tests/signer/test_signer.py
Labels: enhancement
