Repository mozilla/remote-settings, pull requests merged in 2024-01, with the labels that each got.

#521 Add sequence diagrams to ADR 2
  docs/adr/adr_002_packaging_releasing_admin_UI.md
  tests/browser_test.py
Labels: documentation

#525 Pull Kinto Admin from sources
  RemoteSettings.Dockerfile
  bin/build-kinto-admin.sh
  kinto-admin/VERSION
  poetry.lock
  pyproject.toml
Labels: dependencies

#528 Upgrade `kinto-admin` to `3.0.1`
  kinto-admin/VERSION
Labels: dependencies

#519 ADR about Kinto Admin UI releasing and packaging
  docs/adr/adr_002_packaging_releasing_admin_UI.md
Labels: enhancement, documentation

#529 Add Action workflow to bump Kinto Admin
  .github/workflows/scheduled.yaml
Labels: enhancement
