Repository mozilla/remote-settings, pull requests merged in 2024-11, with the labels that each got.

#693 Add missing documentation for JEXL transforms available on Desktop
  docs/target-filters.rst
Labels: documentation

#694 Upgrade kinto to 19.3.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#695 Allow any file extension for attachments
  .secrets.baseline
  config/local.ini
Labels: enhancement

#699 Update documentation about scheduled ingestion scripts
  docs/support.rst
Labels: documentation

#702 Adjusting scheduled workflow to mark the PR's it creates for auto-mere with squash
  .github/workflows/scheduled.yaml
Labels: fix

#704 Backport prod settings into settings of local container
  .secrets.baseline
  config/local.ini
Labels: enhancement

#714 Fix casing in browsertests dockerfile
  BrowserTests.Dockerfile
Labels: enhancement

#711 Add details in attachments bundles client specs docs
  docs/client-specifications.rst
Labels: documentation

#713 Update existing clients features status
  docs/client-specifications.rst
Labels: documentation
