Repository mozilla/remote-settings, pull requests merged in 2025-03, with the labels that each got.

#783 Fix #745: catch error if the related objects are already deleted
  kinto-remote-settings/src/kinto_remote_settings/signer/listeners.py
  kinto-remote-settings/tests/signer/test_plugin_setup.py
Labels: bug

#781 Skip failing login on fork PRs
  .github/workflows/publish.yaml
Labels: docker

#790 Ref #788: Add attachment overwrite in browser tests
  browser-tests/conftest.py
  browser-tests/kinto-logo.jpg
  browser-tests/test_review.py
Labels: enhancement

#792 Upgrade kinto to 20.1.0
  config/local.ini
  config/testing.ini
  poetry.lock
  pyproject.toml
Labels: dependencies

#795 CI - Explicitely ignore gha creds
  RemoteSettings.dockerignore
  browser-tests/.dockerignore
  cronjobs/.dockerignore
Labels: docker

#796 Fixing test_review_existing_record browser test
  browser-tests/test_review.py
Labels: fix

#800 Renaming dockerignore. Named dockerignore files are not a thing.
  .dockerignore
Labels: bug

#802 Update releasing instructions
  README.rst
  browser-tests/README.md
Labels: documentation

#806 Fix #805: prevent crash when since value contains trailing new line
  kinto-remote-settings/src/kinto_remote_settings/changes/views.py
  kinto-remote-settings/tests/changes/test_changeset.py
Labels: bug

#807 Improve jexl filters reporting
  Makefile
  bin/list-target-filters.py
Labels: enhancement

#812 Fix #406: consistency of python versions in CI and Dockerfile
  .github/workflows/ci.yaml
  .readthedocs.yaml
  Makefile
  bin/repo-python-versions.py
  cronjobs/Dockerfile
Labels: enhancement, dependencies, docker

#811 Fix #808: reflect divergence of clients support in JEXL docs
  docs/target-filters.rst
Labels: documentation

#814 Add explicit sphinx config for readthedocs
  .readthedocs.yaml
Labels: documentation

#816 Ref #804: add script to list groups history and useless entries that can be deleted
  bin/groups-history.py
Labels: ops

#817 Do not try to install root project in readthedocs
  .readthedocs.yaml
Labels: documentation

#819 Ref #813: add readthedocs badge
  README.rst
Labels: documentation

#818 Fix #191: remove notions of kinto-signer
  browser-tests/plugins/test_history.py
  cronjobs/src/commands/refresh_signature.py
  kinto-remote-settings/README.rst
  kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py
  kinto-remote-settings/src/kinto_remote_settings/signer/utils.py
  kinto-remote-settings/tests/signer/test_events.py
  kinto-remote-settings/tests/signer/test_plugin_setup.py
Labels: enhancement

#827 Fix #826: update documentation after JEXL normalization
  docs/target-filters.rst
Labels: documentation

#829 Use print() in sync_megaphone cronjob
  cronjobs/src/commands/sync_megaphone.py
Labels: bug

#832 Add option to exclude certain collections from monitor/changes
  kinto-remote-settings/src/kinto_remote_settings/changes/utils.py
  kinto-remote-settings/src/kinto_remote_settings/signer/utils.py
  kinto-remote-settings/tests/changes/config.ini
  kinto-remote-settings/tests/changes/test_changes.py
Labels: enhancement
