Repository mozilla/remote-settings, pull requests merged in 2025-06, with the labels that each got.

#918 Updating admin to 4.0.1
  browser-tests/poetry.lock
  browser-tests/pyproject.toml
  browser-tests/test_review.py
  kinto-admin/VERSION
Labels: dependencies

#924 Ref #911 - Updating documentation on querying/alerting on logs via yardstick
  docs/monitoring.rst
Labels: documentation

#931 fix - fixing doc warnings for highlighting failures on grafana sql blocks
  docs/monitoring.rst
Labels: fix, documentation

#932 Revert "Add Slack notification for ingestion job success/failure (#926)"
  .github/workflows/ingestion-job-publish.yaml
Labels: docker, github_actions
