Repository mozilla/remote-settings, pull requests merged in 2025-02, with the labels that each got.

#741 Fixes #740: Expand patterns in settings
  config/local.ini
  kinto-remote-settings/src/kinto_remote_settings/signer/__init__.py
  kinto-remote-settings/src/kinto_remote_settings/signer/utils.py
  kinto-remote-settings/tests/signer/test_plugin_setup.py
  kinto-remote-settings/tests/signer/test_utils.py
Labels: enhancement

#749 Publish ARM64 Docker image
  .github/workflows/publish.yaml
Labels: docker

#751 Fix publish Github Action
  .github/workflows/ci.yaml
  .github/workflows/publish.yaml
  .github/workflows/scheduled.yaml
Labels: bug, docker

#753 Enable Github Actions updates via Dependabot
  .github/dependabot.yml
Labels: dependencies

#752 Run tests with Python 3.13
  .github/workflows/ci.yaml
Labels: dependencies

#763 Add caching for Docker builds
  .github/workflows/publish.yaml
Labels: docker

#760 Remove Normandy tutorial
  docs/case-studies.rst
  docs/index.rst
  docs/support.rst
  docs/tutorial-normandy-integration.rst
Labels: documentation

#762 Enable buildx to enable multiplatform builds
  .github/workflows/publish.yaml
Labels: bug, docker

#768 Fix #767: bound provided `?_limit` in `/changeset` endpoints
  kinto-remote-settings/src/kinto_remote_settings/changes/utils.py
  kinto-remote-settings/src/kinto_remote_settings/changes/views.py
  kinto-remote-settings/tests/changes/test_changeset.py
Labels: bug

#771 Move browser tests to their own folder
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  README.rst
  RemoteSettings.dockerignore
  browser-tests/.dockerignore
  browser-tests/Dockerfile
  browser-tests/__init__.py
  browser-tests/conftest.py
  browser-tests/kinto-logo.svg
  browser-tests/plugins/__init__.py
  browser-tests/plugins/test_attachment.py
  browser-tests/plugins/test_changes.py
  browser-tests/plugins/test_email.py
  browser-tests/plugins/test_history.py
  browser-tests/plugins/test_signer.py
  browser-tests/poetry.lock
  browser-tests/pyproject.toml
  browser-tests/run.sh
  browser-tests/test_endpoints.py
  browser-tests/test_review.py
  browser-tests/utils.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: docker

#758 Fix #755: Import lambdas into this repo
  Makefile
  README.rst
  cronjobs/.dockerignore
  cronjobs/Dockerfile
  cronjobs/README.md
  cronjobs/poetry.lock
  cronjobs/pyproject.toml
  cronjobs/src/commands/__init__.py
  cronjobs/src/commands/backport_records.py
  cronjobs/src/commands/build_bundles.py
  cronjobs/src/commands/refresh_signature.py
  cronjobs/src/commands/sync_megaphone.py
  cronjobs/src/main.py
  cronjobs/tests/commands/conftest.py
  cronjobs/tests/commands/test_backport_records.py
  cronjobs/tests/commands/test_build_bundles.py
  cronjobs/tests/commands/test_refresh_signature.py
  cronjobs/tests/commands/test_sync_megaphone.py
  cronjobs/tests/test_main.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: dependencies
