Repository mozilla/remote-settings, pull requests merged in 2025-08, with the labels that each got.

#979 Safety check on `actionlint` binary
  .github/workflows/ci.yaml
Labels: github_actions

#980 Upgrade to kinto 23.1.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#976 Log when clients don't receive the expected changeset timestamp
  kinto-remote-settings/src/kinto_remote_settings/changes/views.py
  kinto-remote-settings/tests/changes/test_changeset.py
Labels: enhancement

#978 Fix #977 - Returning 400 responses to clients when `_expected` value is less than `_since` value
  kinto-remote-settings/src/kinto_remote_settings/changes/views.py
  kinto-remote-settings/tests/changes/test_changes.py
  kinto-remote-settings/tests/changes/test_changeset.py
Labels: bug

#989 Align demo/local configuration with our prod config
  config/local.ini
  config/testing.ini
Labels: enhancement
